nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Origin', 'Content-Type', 'Authorization']
        # allow_headers: ['Content-Type', 'Authorization']
        # allow_headers: ['Content-Type', 'Authorization', 'origin', 'accept', '*']
        # allow_headers: ['Content-Type', 'Authorization', 'origin', 'accept', 'bearer']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        # '^/api/':
        #     allow_origin: ['http://localhost:4200']
        #     allow_headers: ['origin', 'content-type', 'authorization']
        #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        #     max_age: 3600
        '^/': null
